version: '3'
services:

  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DATABASE_URL=postgresql://task82p_user:T6oVge4XQwNh662KeScfvFD58zZWBKJv@dpg-crietojv2p9s738h798g-a.oregon-postgres.render.com/task82p
    restart: "no"

  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "8082:8082"
    environment:
      - PORT=8082
      - DATABASE_URL=postgresql://task82p_user:T6oVge4XQwNh662KeScfvFD58zZWBKJv@dpg-crietojv2p9s738h798g-a.oregon-postgres.render.com/task82p
    restart: "no"